### ISSUE TITLE
(Fabric) Startup error with Farmer's Delight Refabricated.

### ISSUE THREAD

**Issue by HeyitsNyixie** [MrCrayfish/MrCrayfishFurnitureMod-Refurbished#11]
I cannot load old worlds or create new worlds with Farmer's Delight Refabricated installed. I'm using Refabricated to run other add-ons that are no longer compatible with the older fabric version.

Here is the error I received upon trying to boot a world:
"The game crashed whilst mouseclicked event handler
Error: java.lang.NoSuchMethodError: 'net.minecraft.class_1799 net.minecraft.class_1799.getRecipeRemainder()'"

**Comment by MrCrayfish** [comment]
Thanks for the report. Fixed in https://github.com/MrCrayfish/MrCrayfishFurnitureMod-Refurbished/commit/33423a8060d2d6927233ed38e7cad0850842a1e1
