### ISSUE TITLE
electricity isn't working

### ISSUE THREAD

**Issue by Jaydinator06** [MrCrayfish/MrCrayfishFurnitureMod-Refurbished#14]
my electrical generator is on and running, however I keep running into the same issue. I'll connect my electronics to it and they'll work, but for some reason they still say that they are missing power. I don't want to have to see "missing power" every time I cross by my kitchen or something. it's really annoying, what do I do?

**Comment by MrCrayfish** [comment]
Thanks for the report. This has been fixed in https://github.com/MrCrayfish/MrCrayfishFurnitureMod-Refurbished/commit/7d108fe4ac183c0a5a686e16788b4a2e597cf485

**Comment by imgoodvr** [comment]
how do i use an electricity generator
