### ISSUE TITLE
Compatibility issue with Roughly Enough Items - Fabric 1.20.1

### ISSUE THREAD

**Issue by ExoJordy** [MrCrayfish/MrCrayfishFurnitureMod-Refurbished#16]
The Game Crashes with Roughly Enough Items installed on fabric 1.20.1 when right clicking the Freezer, Microwave and oven (with or without power enabled) 

Crashlog here -  https://pastebin.com/uaw2Ns8S

I have opened the game without the below mods enabled:

Roughly Enough Resources (rer-2.9.0.jar)
Roughly Enough Professions (RoughlyEnoughProfessions-fabric.1.20.1-2.0.2.jar)
Roughly Enough Items (RoughlyEnoughItems-12.1.740-fabric.jar)

Let me know if you need any more info regarding this crash.

**Comment by Jab125** [comment]
> The Game Crashes with Roughly Enough Items installed on fabric 1.20.1 when right clicking the Freezer, Microwave and oven (with or without power enabled)
> 
> Crashlog here - https://pastebin.com/uaw2Ns8S
> 
> I have opened the game without the below mods enabled:
> 
> Roughly Enough Resources (rer-2.9.0.jar) Roughly Enough Professions (RoughlyEnoughProfessions-fabric.1.20.1-2.0.2.jar) Roughly Enough Items (RoughlyEnoughItems-12.1.740-fabric.jar)
> 
> Let me know if you need any more info regarding this crash.

Tell @shedaniel to figure out how to fix it, but it seems like REI is not setup for enum extension

**Comment by Jab125** [comment]
Actually, this looks like a bug where the custom enums aren't registered.

**Comment by MrCrayfish** [comment]
Thanks for the report. This has been fixed in https://github.com/MrCrayfish/MrCrayfishFurnitureMod-Refurbished/commit/cde1251a2dfa1ce140119f8574338340699bc4fc

**Comment by lihaan** [comment]
Any rough idea when will this patch be pushed to release? Thanks!
