### ISSUE TITLE
Refurbished Furniture is Causing a Crash

### ISSUE THREAD

**Issue by pommellie** [MrCrayfish/MrCrayfishFurnitureMod-Refurbished#17]
Using 
- Minecraft 1.20.1
- Fabric 0.16.0
- Refurbished Furniture 1.0.3
- Framework 0.7.6

I tend to play with a lot of mods and have been going through little by little to determine which mod has been causing the game to crash on launch. Refurbished Furniture, sadly, is the one that has been causing the issue, but I cannot figure out why.

Because of this, I did try launching the game with ONLY Refurbished Furniture and its dependency (Framework) alongside Fabric API (just in case), and the crash is still occurring.

Launcher Log (with other mods):

Launcher Log (without other mods):

(I have checked Crash Reports as well, and there are none related to this mod; only launcher logs.)

**Comment by TranquilStar** [comment]
do you know what version fabric you have installed, I have 0.16.0 installed and it works, I will however open a ticket that this mod is incompatible with mighty mail.

also make sure to see if any mods need updated.

**Comment by TranquilStar** [comment]
you might still wanna provide a crash log, I was crashing as well but it seems that my issue is slightly resolved, I dont know if you have mighty mail installed but that was what was causing my issue, which I will be opening a ticket for.

**Comment by pommellie** [comment]
I do not have Mighty Mail installed, and I do not know which crash log to include because none was generated for the crash.

**Comment by MrCrayfish** [comment]
Try redownloading the mod as it may be corrupted. Also try a fresh install of everything. Also I've removed your gist link as it contained sensitive information (IP). Use https://mclo.gs/ to hide this in the future.

**Comment by pommellie** [comment]
Fresh install/redownload fixed it! Thank you so much!

Also, I didn't even realize that it had my IP on there. O.O Thank you so much for removing it and I have bookmarked the link you suggested for future use. (Thankfully, I use a VPN, but still that is worrisome. Thank you so much for informing me of that and removing the links.)

**Comment by yan2-cyber** [comment]
Здраствуйте, мод просто замечательный ! 
Но прошу помогите мне с одной проблемой. Дело в том что когда я использую кухоный нож он не режит хлеб на ломтики хлеба, также с пиццей не могу порубить на кусочки. 
Прошу о помощи с данной проблемой.
Может быть это какая та ошибка ?
