### ISSUE TITLE
[FABRIC] Gamecrash with better combat

### ISSUE THREAD

**Issue by BoxingJoost** [MrCrayfish/MrCrayfishFurnitureMod-Refurbished#2]
Fabric:
1.20.1 0.16.0

Mods:
Fabric API
Framework
Furniture Refurbished
Player Animation Lib
Cloth Config API
Better Combat

My game crashed when i try to hold a knife/spatula while having the Better Combat mod activated.

[crash-2024-07-20_14.41.37-client.txt](https://github.com/user-attachments/files/16321118/crash-2024-07-20_14.41.37-client.txt)

**Comment by SAGESSE-CN** [comment]
https://github.com/MrCrayfish/MrCrayfishFurnitureMod-Refurbished/blob/ee0a81e3c7077b638dc16cbe5d5cd3939f1266bc/fabric/src/main/java/com/mrcrayfish/furniture/refurbished/asm/ClientLoader.java#L27

because of this asm, it will cause all ItemStack mixin of fabric to fail!!

**Comment by MrCrayfish** [comment]
@SAGESSE-CN Thanks for pointing this out. It seems I will have to disable the recipe book support on Fabric.

**Comment by CFog1** [comment]
> @SAGESSE-CN Thanks for pointing this out. It seems I will have to disable the recipe book support on Fabric.

this happens to me on forge I think

**Comment by MrCrayfish** [comment]
Thanks for the report. Fixed in https://github.com/MrCrayfish/MrCrayfishFurnitureMod-Refurbished/commit/33423a8060d2d6927233ed38e7cad0850842a1e1
