### ISSUE TITLE
All lights sources say power is missing even though power is connected

### ISSUE THREAD

**Issue by bluegamer22421** [MrCrayfish/MrCrayfishFurnitureMod-Refurbished#22]
![image](https://github.com/user-attachments/assets/e22cd737-b0b7-4d77-a3fd-0c8192c5cf04)
Mod version: 1.20.1-1.03
forge version: 47.3.5 1.20.1 forge
im using 18 more mods if thats a problem i can send the mod names
also theres nowhere to ask but how do i switch channels on a tv? or theres just one? Because when im trying to switch its just showing me tv static and nothing else.
![image](https://github.com/user-attachments/assets/b1dfb760-ff52-4d6d-a80a-fcd80b5ef0c9)

**Comment by MrCrayfish** [comment]
Fixed as part of this commit https://github.com/MrCrayfish/MrCrayfishFurnitureMod-Refurbished/commit/a6797b03a2d44526e7aeac9c3cfb33285ab04b10
