### ISSUE TITLE
[CRASH] When loading the game, it causes errors between Origins and Qu Enchantments [Fabric 0.16.0/1.20.1]

### ISSUE THREAD

**Issue by pokesmells** [MrCrayfish/MrCrayfishFurnitureMod-Refurbished#3]
https://mclo.gs/9q4TyGa

I understand that this stack trace shows 2 different mods, but it only happens when I have the furniture mod enabled.

**Comment by MrCrayfish** [comment]
Thanks for the report. Fixed in https://github.com/MrCrayfish/MrCrayfishFurnitureMod-Refurbished/commit/33423a8060d2d6927233ed38e7cad0850842a1e1
