### ISSUE TITLE
[1.21.1]Generator loses fuel when re-entering the world

### ISSUE THREAD

**Issue by Ironnoob73** [MrCrayfish/MrCrayfishFurnitureMod-Refurbished#35]
[https://gist.github.com/Ironnoob73/3c30b3774f065f8478c903480a3a4f9f](https://gist.github.com/Ironnoob73/3c30b3774f065f8478c903480a3a4f9f)

**Comment by MrCrayfish** [comment]
Fixed in 3eae0d79b5759d2bb7d013b510329e427dc1fd25
