### ISSUE TITLE
Any plan to backport to 1.19.2 forge?

### ISSUE THREAD

**Issue by QianFuv** [MrCrayfish/MrCrayfishFurnitureMod-Refurbished#4]

**Comment by MrCrayfish** [comment]
There is the possibility of a backport but it's very low on the priority. I would not expect it anytime soon.

**Comment by MrCrayfish** [comment]
Available soon!
https://github.com/MrCrayfish/MrCrayfishFurnitureMod-Refurbished/tree/1.19.2

**Comment by QianFuv** [comment]
Thank you very much! Have a wonderful day!
