### ISSUE TITLE
[1.21.1]Mailboxe sometimes doesn't actually clear its inventory

### ISSUE THREAD

**Issue by Ironnoob73** [MrCrayfish/MrCrayfishFurnitureMod-Refurbished#40]
I'm not sure how to reproduce this issue, but trying to send mail to an unloaded chunk may cause item duplication issues.
Sometimes after sending a mail, the mailbox looks empty, but after some chunk loading and unloading operations (the simple way to reproduce is to exit and re-enter the world), there is a chance that the item you sent last time will appear in it.
Sometimes packages will appear in your mailbox that you have already unpacked (I am not sure if this is a problem if you use a separate mailbox. To prevent the mailbox from being filled up, I use a hopper to export emails directly).

**Comment by MrCrayfish** [comment]
Thanks for the report. After some investigating, there may be an issue where the mailing queue is restored and resends the mail (as you described). I will have a hotfix out soon.

**Comment by MrCrayfish** [comment]
Thanks for the report. Fixed in d942686adf119cd6167eb213e1de451dd6cb42fa
