### ISSUE TITLE
Missing Recipe

### ISSUE THREAD

**Issue by BerlinAlexK93** [MrCrayfish/MrCrayfishFurnitureMod-Refurbished#41]
Missing Recipe for the Television Remote in Minecraft NeoForge 1.21

There is no Recipe in JEI and no Recipe in the MrCrayfish Workbench. 

Please add it to the Game, thnak you :)

**Comment by MrCrayfish** [comment]
Thanks for the report. Fixed in eafb088a74a19021a62ec1f2a5b3c3b1eea62db8
