### ISSUE TITLE
[Suggestion] Config option to disable power usage.

### ISSUE THREAD

**Issue by Greenjoe12345** [MrCrayfish/MrCrayfishFurnitureMod-Refurbished#44]
It would be good to have a config option to disable power usage on electrical items, for building in creative, so there isn't a need to place a bunch of generators to power whatever it is you are making.

**Comment by MrCrayfish** [comment]
Thanks for the suggestion. Added in 1194a03079e0295f16ffbd395a0f4d8f415db492
