### ISSUE TITLE
["Bug"] Version Checker is Failing

### ISSUE THREAD

**Issue by andrew0030** [MrCrayfish/MrCrayfishFurnitureMod-Refurbished#46]
Hey, I'm a fellow mod developer, and while I was recently working on some of my code, I discovered that pretty much **all of your mods**, you set up to check for updates using the forge update checker are failing.
I did some investigating and I assume the issue probably originates from the fact that the website either blocks the request or delays it to long. Ofc take this with a grain of salt as I am no expert when it comes to this stuff.
But yeah accessing one of the links: https://mrcrayfish.com/api/mod_update/forge/refurbished_furniture results with a browser check.

![image](https://github.com/user-attachments/assets/d2248fd8-4025-4bc1-97c6-624569808268)

**Comment by MrCrayfish** [comment]
Yeah, I am having an issue with my host who thinks all the requests to my website is a DDOS attack, and is automatically turning on a setting to add verification.

**Comment by andrew0030** [comment]
Glad to hear you are aware, wasn't sure so I decided to come by and leave a message.

**Comment by MrCrayfish** [comment]
As of right now, it seems my host is now allowing the connections to go through without ddos captcha. Going to close this issue.
