### ISSUE TITLE
Recipe book for stove causes the output item to disappear.

### ISSUE THREAD

**Issue by khazenor** [MrCrayfish/MrCrayfishFurnitureMod-Refurbished#48]
## Versions:
- minecraft: 1.21
- neoforge: 21.0.167
## Mods:
- refurbished_furniture-neoforge-1.21-1.0.6
- framework-neoforge-1.21-0.9.1

## Steps:
1. Start a new world
2. Run /recipe give <playname> refurbished_furniture:baking/baked_potato
3. Open a stove: ![image](https://github.com/user-attachments/assets/645ce91a-bc98-4045-91f8-56df1c482397)
4. Click on the baked potato recipe and wait for the potato to finish cooking: 
![image](https://github.com/user-attachments/assets/0847097c-5d49-4138-b46c-efb8ac3377b6)
5. Click on the baked potato recipe again without taking out the baked potato from the output: 
![image](https://github.com/user-attachments/assets/368adf49-5311-410b-adb6-a2e4b25544f9)

## Outcome:
- The baked potato in the output disappeared

## Desired outcome:
- The baked potato in the output should still be there when the recipe is clicked

**Comment by MrCrayfish** [comment]
Thanks for the report and detailed steps! Fixed in adcd1e2a7019ad4acc5ffcf2e339d42331a6f8c0

**Comment by khazenor** [comment]
Awesome!  Thank you so much! (sorry for the late response haha)
