### ISSUE TITLE
NeoForge tags use `neoforge` namespace on 1.20.4 when they should be using `forge`

### ISSUE THREAD

**Issue by Jab125** [MrCrayfish/MrCrayfishFurnitureMod-Refurbished#5]
See https://github.com/neoforged/NeoForge/blob/1.20.4/src/main/java/net/neoforged/neoforge/common/Tags.java

NeoForge didn't switch to using `neoforge` for tags, instead switching directly from `forge` to `c` in 1.20.5.

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishFurnitureMod-Refurbished/commit/c773f41ccf21d18837f4b82d39e34d7c993bf4a2 and switched versions above 1.20.5 to use `c`
