### ISSUE TITLE
Freezer not creating ice -- Minecraft 1.19.2, Mod (Forge) Ver: 1.0.6

### ISSUE THREAD

**Issue by cparks1** [MrCrayfish/MrCrayfishFurnitureMod-Refurbished#52]
Minecraft Version: 1.19.2
Mod Version (Forge): 1.0.6

Putting a water bucket into the freezer slot of a fridge that is powered and on does not provide a block of ice, but does remove the water from the bucket.

I believe the issue is that [a fix you pushed to resolve this back in July](https://github.com/MrCrayfish/MrCrayfishFurnitureMod-Refurbished/commit/a92a01e1df93caac4206bcda279de02ef9535e48) was undone by [a later commit to the 1.19.2 branch made in August](https://github.com/MrCrayfish/MrCrayfishFurnitureMod-Refurbished/commit/e056b671cba0a6867a9037e583d48da1eeda9dbc#diff-d35ff16eafe72e243db5215ba80389e7664ade2c08451c3a7cf416028c7b7c0b)

**Comment by cparks1** [comment]
I've created [a pull request](https://github.com/MrCrayfish/MrCrayfishFurnitureMod-Refurbished/pull/53) that will fix the issue, if I'm correct about what's causing the problem.

**Comment by MrCrayfish** [comment]
Fixed in 51acfa398cc295aed6403fe363b31c6fbe1e0d3c

**Comment by MrCrayfish** [comment]
Fixed in 51acfa398cc295aed6403fe363b31c6fbe1e0d3c
