### ISSUE TITLE
Generator not rendering properly when powered

### ISSUE THREAD

**Issue by Allomere** [MrCrayfish/MrCrayfishFurnitureMod-Refurbished#54]
![image](https://github.com/user-attachments/assets/689d2edc-ac9f-4b12-9a87-65e5b49aabe3)
[latest.log](https://github.com/user-attachments/files/17422093/latest.log)

**Comment by MrCrayfish** [comment]
Not sure on this one since it's just a normal block and uses the vanilla model system, not custom. Try removing any performance mods one by one you may be using since they usually modify rendering/lighting.

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishFurnitureMod-Refurbished/commit/e200e84c3b784e4a2358b0a4e7b019ae177528fb
