### ISSUE TITLE
Grill Visuals not appearing

### ISSUE THREAD

**Issue by Chrispyhreme** [MrCrayfish/MrCrayfishFurnitureMod-Refurbished#55]
So I just downloaded this mod for my server, everything works fine except the grill, theres no visuals of me adding coal and putting the meat on the grill. I cannot tell whether what I am cooking is done or if I've ran out of coal. I hope this gets fixed thank you

**Comment by MrCrayfish** [comment]
Thanks for the report. I will look into this soon

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishFurnitureMod-Refurbished/commit/84edfd5c13745c40f8e8e4723b3a4f4d9ad1efac
