### ISSUE TITLE
version 1.0.6 neoforge - no light emission, strange transparency, and missing fan model

### ISSUE THREAD

**Issue by darock830** [MrCrayfish/MrCrayfishFurnitureMod-Refurbished#57]
Electrical furniture that emits light appears transparent but almost like it is filled with water, and when light is turned on, it becomes fully invisible, and there is no light emission. The ceiling fan can be powered and rotates, but it is missing texture and shows up as a purple and black cube that rotates.

I am using
minecraft version 1.21.1
neoforge launcher 21.1.75
Furniture mod version 1.0.6

latest log is attached
[latest.log](https://github.com/user-attachments/files/17591951/latest.log)

**Comment by MrCrayfish** [comment]
It's your shader pack
