### ISSUE TITLE
Generator runs out once out of render distance.

### ISSUE THREAD

**Issue by BreadTM-2006** [MrCrayfish/MrCrayfishFurnitureMod-Refurbished#58]
When ever I leave my massive base I have made, my generator which is powering stair case lights always seems to run out instantly when it should have about an hour of running time, you may want to look into it or may just be a problem on my side but always a good idea to have a look into just in case.

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishFurnitureMod-Refurbished/commit/f172748e98d5a8c1439143f6ca9314a9c08b12f5
