### ISSUE TITLE
Incompatibility with betternether

### ISSUE THREAD

**Issue by antoni0C0des** [MrCrayfish/MrCrayfishFurnitureMod-Refurbished#6]
It is not possible to join a server when this mod and its dependency are installed. Errors point towards betternether and failure to register entries. Here are some logs: https://mclo.gs/reTXoar a client log - there is a crash, & https://mclo.gs/fLCSg3k a client log - it reports how it failed to register. Server logs output no useful info

**Comment by therealyocow** [comment]
Seconding this. Here are my logs, in which **ONLY** BetterNether, Refurbished, and all of their dependencies are installed to rule out any other problematic mods. Client: https://mclo.gs/BAFyLSN Server: https://mclo.gs/pjZallT

I did not experience any crashes, but I was unable to join the server.

**Comment by therealyocow** [comment]
Seems to have been fixed as of 1.0.3!

**Comment by MrCrayfish** [comment]
Thanks for the update. Closing now.
