### ISSUE TITLE
Items are incompatible with texture packs

### ISSUE THREAD

**Issue by Tzhu14** [MrCrayfish/MrCrayfishFurnitureMod-Refurbished#61]
I'm playing MineCraft 1.20.1 with Fabric 0.16.5. When I use texture packs, the appearance of the furnitures are still like the original looking of MineCraft. To illustrate the problem, I provide a screenshot below. The appearance of the blocks match the texture pack, while the birch wood chair and the dark oak table still look like there isn't any texture pack. This problem doesn't appear in your old furniture mod, it only appears in the refurbished mod.
![屏幕截图 2024-11-09 120855](https://github.com/user-attachments/assets/f4568d59-8f45-4027-a60f-5de7868b4ee4)

**Comment by MrCrayfish** [comment]
The furniture uses custom textures now, not existing vanilla textures. Not a bug.
