### ISSUE TITLE
[Forge] Can't sort this mod item inventory with quark inventory sorting

### ISSUE THREAD

**Issue by Urias0** [MrCrayfish/MrCrayfishFurnitureMod-Refurbished#7]
Hey not sure if i should report that here or to the quark wiki but to explain , there's a keybind to sort inventory and containers but i can't sort anything in the drawer , fridge and cabinet , other than that i just want to say i'm glad to see the new version of this mod , absolutely love it !

**Comment by MrCrayfish** [comment]
I believe you need to allow them in the config of Quark.
