### ISSUE TITLE
won't config to Minecraft server

### ISSUE THREAD

**Issue by crunmchy** [MrCrayfish/MrCrayfishFurnitureMod-Refurbished#71]
I am on a Minecraft server with some friends. I had to download a modpack that the owner made themselves (all the mods are the correct versions, I checked), to use the server. I am also using prism launcher on MacOs for the VC mod in it if that makes a difference. However, every time I try to join the server, it always says the server couldn't config this specific mod. I'm not sure if it's a prism issue, Mac issue, or a mod issue, so here I am.

**Comment by MrCrayfish** [comment]
What was the fix?

**Comment by crunmchy** [comment]
I am not sure, but the mod seemed to not be working anytime I had it paired
with your Controllable mod.
