### ISSUE TITLE
[Forge] Freeze doesn't produce ice while active

### ISSUE THREAD

**Issue by Urias0** [MrCrayfish/MrCrayfishFurnitureMod-Refurbished#8]
Turned it on with a bucket of water in it , i saw the progress bar go and my bucket emptied but no ice anywhere , checked the fridge just in case but nothing

**Comment by MrCrayfish** [comment]
Thanks for the report. Fixed in https://github.com/MrCrayfish/MrCrayfishFurnitureMod-Refurbished/commit/a92a01e1df93caac4206bcda279de02ef9535e48
