### ISSUE TITLE
Crashing as soon as i enter the game (1.20.6 no other mods installed)

### ISSUE THREAD

**Issue by Vaggelis117** [MrCrayfish/MrCrayfishFurnitureMod-Refurbished#82]
The game crashed whilst ticking player
Error: java.lang.ClassCastException: class net.minecraft.server.level.ServerLevel cannot be cast to class com.mrcrayfish.furniture.refurbished.electricity.LinkManager$Access (net.minecraft.server.level.ServerLevel is in module minecraft@1.20.6 of loader 'TRANSFORMER' @53c99b09; com.mrcrayfish.furniture.refurbished.electricity.LinkManager$Access is in module refurbished_furniture@1.0.6 of loader 'TRANSFORMER' @53c99b09)

Hello i really would like to use this mod ive tried removing all other mods but this still appears im using forge and have only framework downloaded other than the mod

**Comment by MrCrayfish** [comment]
Unfortunately I have discontinued support for Minecraft 1.20.6, so I will not be fixing bugs for that version. I recommend you downgrade to Minecraft 1.20.1 or update to Minecraft 1.21.1/4 as these versions I support (based on what the majority of the community uses).

**Comment by MrCrayfish** [comment]
If the crash happens on those versions, feel free to open another issue.
